-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 5.7
-- Tue Mar 05 22:00:46 2019

-- parameterized module component declaration
component CLKPLL
    port (CLKI: in  std_logic; ENCLKOP: in  std_logic; 
        ENCLKOS: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : CLKPLL
    port map (CLKI=>__, ENCLKOP=>__, ENCLKOS=>__, CLKOP=>__, CLKOS=>__);
