-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 4.6
-- Sat Mar 02 19:45:14 2019

-- parameterized module component declaration
component counter
    port (Clock: in  std_logic; Clk_En: in  std_logic; 
        Aclr: in  std_logic; Q: out  std_logic_vector(1 downto 0));
end component;

-- parameterized module component instance
__ : counter
    port map (Clock=>__, Clk_En=>__, Aclr=>__, Q(1 downto 0)=>__);
