-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 4.6
--C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n counter -lang vhdl -synth lse -bb -arch xo3c00a -type counter -up -width 2 -cnt_low 0 -cnt_up 3 

-- Sat Mar 02 19:45:14 2019

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO3L;
use MACHXO3L.components.all;
-- synopsys translate_on

entity counter is
    port (
        Clock: in  std_logic; 
        Clk_En: in  std_logic; 
        Aclr: in  std_logic; 
        Q: out  std_logic_vector(1 downto 0));
end counter;

architecture Structure of counter is

    -- internal signal declarations
    signal scuba_vlo: std_logic;
    signal scuba_vhi: std_logic;
    signal idataout0: std_logic;
    signal idataout1: std_logic;
    signal co0: std_logic;
    signal cnt_ci: std_logic;
    signal tdataout0: std_logic;
    signal tdataout1: std_logic;

    -- local component declarations
    component CU2
        port (CI: in  std_logic; PC0: in  std_logic; PC1: in  std_logic; 
            CO: out  std_logic; NC0: out  std_logic; NC1: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    FF_1: FD1P3DX
        port map (D=>idataout0, SP=>Clk_En, CK=>Clock, CD=>Aclr, 
            Q=>tdataout0);

    FF_0: FD1P3DX
        port map (D=>idataout1, SP=>Clk_En, CK=>Clock, CD=>Aclr, 
            Q=>tdataout1);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    cnt_cia: FADD2B
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>cnt_ci, S0=>open, 
            S1=>open);

    cnt_0: CU2
        port map (CI=>cnt_ci, PC0=>tdataout0, PC1=>tdataout1, CO=>co0, 
            NC0=>idataout0, NC1=>idataout1);

    Q(0) <= tdataout0;
    Q(1) <= tdataout1;
end Structure;

-- synopsys translate_off
library MACHXO3L;
configuration Structure_CON of counter is
    for Structure
        for all:CU2 use entity MACHXO3L.CU2(V); end for;
        for all:FADD2B use entity MACHXO3L.FADD2B(V); end for;
        for all:FD1P3DX use entity MACHXO3L.FD1P3DX(V); end for;
        for all:VHI use entity MACHXO3L.VHI(V); end for;
        for all:VLO use entity MACHXO3L.VLO(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
