-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.10.3.144
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component counter
        port (Clock: in std_logic; Clk_En: in std_logic; 
        Aclr: in std_logic; Q : out std_logic_vector(1 downto 0)
    );
    end component;

    signal Clock: std_logic := '0';
    signal Clk_En: std_logic := '0';
    signal Aclr: std_logic := '0';
    signal Q : std_logic_vector(1 downto 0);
begin
    u1 : counter
        port map (Clock => Clock, Clk_En => Clk_En, Aclr => Aclr, Q => Q
        );

    Clock <= not Clock after 5.00 ns;

    process

    begin
      Clk_En <= '0' ;
      wait for 100 ns;
      wait until Aclr = '0';
      for i in 0 to 100 loop
        wait until Clock'event and Clock = '1';
        Clk_En <= '1' after 1 ns;
      end loop;
      for i in 0 to 10 loop
        wait until Clock'event and Clock = '1';
        Clk_En <= '0' after 1 ns;
      end loop;
      Clk_En <= '1' ;
      wait;
    end process;

    process

    begin
      Aclr <= '1' ;
      wait for 100 ns;
      Aclr <= '0' ;
      wait;
    end process;

end architecture test;
